#!/usr/bin/env bash
#
# setup-usbtmc.sh
#
# 1. Loads the usbtmc kernel driver
# 2. Verifies that a USBTMC device is present
# 3. Creates a single udev rule (KERNEL=="usbtmc*") granting the invoking
#    (non-root) user access to ANY USBTMC device
# 4. Reloads and applies udev rules
# 5. Runs a live *IDN? query as the target user to confirm access works
#
# Usage: sudo ./setup-usbtmc.sh
#
set -euo pipefail

RULE_FILE="/etc/udev/rules.d/99-usbtmc.rules"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
log()  { echo "[*] $*"; }
err()  { echo "[!] $*" >&2; }

# ---------------------------------------------------------------------------
# 0. Sanity checks
# ---------------------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
    err "This script needs root privileges (loading kernel modules, writing" \
        "to /etc/udev/rules.d, reloading udev). Re-run with sudo."
    exit 1
fi

# Figure out which "real" (non-root) user should get access to the device.
# Prefer SUDO_USER (set when invoked via sudo); fall back to logname.
TARGET_USER="${SUDO_USER:-$(logname 2>/dev/null || true)}"

if [[ -z "${TARGET_USER}" || "${TARGET_USER}" == "root" ]]; then
    err "Could not determine a non-root user to grant access to."
    err "Run this script with 'sudo' from your normal user account, e.g.:"
    err "    sudo ./setup-usbtmc.sh"
    exit 1
fi

log "Granting USBTMC device access to user: ${TARGET_USER}"

# Resolve the user's *actual* primary group. We can't assume a group named
# after the username exists (that's only true with "user private groups",
# which not every distro enables) -- using the wrong/nonexistent group name
# causes udev to silently fail to apply it, leaving the device root-only.
TARGET_GROUP="$(id -gn "${TARGET_USER}" 2>/dev/null || true)"

if [[ -z "${TARGET_GROUP}" ]]; then
    err "Could not resolve a primary group for user '${TARGET_USER}'."
    exit 1
fi

log "Resolved primary group: ${TARGET_GROUP}"

# ---------------------------------------------------------------------------
# 1. Load the usbtmc driver
# ---------------------------------------------------------------------------
log "Loading usbtmc kernel module..."
if ! modprobe usbtmc; then
    err "Failed to load the usbtmc module. Is it available for your kernel?"
    exit 1
fi

# Give the kernel/udev a moment to enumerate the device node(s)
sleep 1

# ---------------------------------------------------------------------------
# 2. Check that a USBTMC device node exists
# ---------------------------------------------------------------------------
shopt -s nullglob
devices=(/dev/usbtmc*)
shopt -u nullglob

if [[ ${#devices[@]} -eq 0 ]]; then
    err "No /dev/usbtmc* device found after loading the driver."
    err "Make sure the instrument is powered on and connected, then re-run."
    exit 1
fi

log "Found ${#devices[@]} USBTMC device(s): ${devices[*]}"

# ---------------------------------------------------------------------------
# 3. Write a single udev rule matching all usbtmc-class devices
# ---------------------------------------------------------------------------
log "Writing udev rule to ${RULE_FILE} ..."
{
    echo "# Auto-generated by setup-usbtmc.sh"
    echo "# Grants user '${TARGET_USER}' access to all USBTMC instruments"
    echo "# Rule 1: the kernel usbtmc driver's char device (/dev/usbtmcN) --"
    echo "#   used by direct read/write access (cat, echo, low-level tools)"
    echo "KERNEL==\"usbtmc*\", MODE=\"0660\", GROUP=\"${TARGET_GROUP}\", TAG+=\"uaccess\""
    echo "# Rule 2: the raw USB device node (/dev/bus/usb/BUS/DEV) --"
    echo "#   used by libusb-based tools (e.g. pyvisa-py, pyusb)"
    echo "SUBSYSTEM==\"usb\", DRIVERS==\"usbtmc\", MODE=\"0660\", GROUP=\"${TARGET_GROUP}\", TAG+=\"uaccess\""
} > "${RULE_FILE}"

chmod 644 "${RULE_FILE}"

# ---------------------------------------------------------------------------
# 4. Reload and apply udev rules
# ---------------------------------------------------------------------------
log "Reloading udev rules..."
udevadm control --reload-rules

log "Triggering udev to apply rules to existing devices..."
udevadm trigger --subsystem-match=usbtmc
udevadm trigger --subsystem-match=usb

log "Done. If the device was already plugged in, unplug and replug it"
log "(or reboot) to guarantee the new permissions take effect."
log "Rule file: ${RULE_FILE}"

# ---------------------------------------------------------------------------
# 5. Show resulting permissions so you can verify it actually applied
# ---------------------------------------------------------------------------
echo
log "Current device node permissions:"
for dev in "${devices[@]}"; do
    ls -l "${dev}" 2>/dev/null || true

    # Also resolve and show the underlying raw /dev/bus/usb/BUS/DEV node,
    # which is what libusb-based tools (pyvisa-py, pyusb) actually open.
    syspath="$(udevadm info -q path -n "${dev}" 2>/dev/null || true)"
    usb_syspath="$(udevadm info -a -p "${syspath}" 2>/dev/null \
        | awk -F'"' '/looking at parent device/{p=$2} /DEVTYPE=="usb_device"/{print p; exit}')"
    if [[ -n "${usb_syspath}" ]]; then
        busnum="$(udevadm info -q property -p "${usb_syspath}" 2>/dev/null | awk -F= '/^BUSNUM=/{print $2}')"
        devnum="$(udevadm info -q property -p "${usb_syspath}" 2>/dev/null | awk -F= '/^DEVNUM=/{print $2}')"
        if [[ -n "${busnum}" && -n "${devnum}" ]]; then
            raw_node="/dev/bus/usb/${busnum}/${devnum}"
            log "  Raw USB node for ${dev}:"
            ls -l "${raw_node}" 2>/dev/null || err "  Could not stat ${raw_node}"
        fi
    fi
done
echo
log "If the group shown above is NOT '${TARGET_GROUP}', or the permission"
log "bits aren't 'rw-rw----', unplug/replug the instrument and re-check:"
log "    ls -l /dev/usbtmc*"
log "Also confirm you're actually in that group:"
log "    id ${TARGET_USER}"

# ---------------------------------------------------------------------------
# 6. Functional test: query *IDN? as the target (non-root) user
# ---------------------------------------------------------------------------
echo
log "Testing device access as user '${TARGET_USER}' (running '*IDN?' query)..."
for dev in "${devices[@]}"; do
    log "  ${dev}:"

    write_err="$(sudo -u "${TARGET_USER}" bash -c "echo '*IDN?' > '${dev}'" 2>&1 1>/dev/null)" \
        && write_ok=1 || write_ok=0

    if [[ "${write_ok}" -ne 1 ]]; then
        err "    Write failed as ${TARGET_USER}: ${write_err}"
        err "    Permissions likely haven't applied yet -- unplug/replug the"
        err "    instrument (or reboot) and re-run this script."
        continue
    fi

    response="$(sudo -u "${TARGET_USER}" timeout 3 cat "${dev}" 2>/dev/null || true)"
    if [[ -n "${response}" ]]; then
        log "    Response: ${response}"
    else
        err "    Write succeeded but no response was read back within 3s."
        err "    Permissions look correct; this may just mean the instrument"
        err "    didn't reply to *IDN? or needs more time -- try manually:"
        err "        echo '*IDN?' > ${dev} && cat ${dev}"
    fi
done
